var searchData=
[
  ['base_5fclass_4994',['base_class',['../structcereal_1_1base__class.html',1,'cereal']]],
  ['base_5fclass_5fid_4995',['base_class_id',['../structcereal_1_1traits_1_1detail_1_1base__class__id.html',1,'cereal::traits::detail']]],
  ['base_5fclass_5fid_5fhash_4996',['base_class_id_hash',['../structcereal_1_1traits_1_1detail_1_1base__class__id__hash.html',1,'cereal::traits::detail']]],
  ['basecastbase_4997',['BaseCastBase',['../structcereal_1_1traits_1_1detail_1_1BaseCastBase.html',1,'cereal::traits::detail']]],
  ['basereaderhandler_4998',['BaseReaderHandler',['../structBaseReaderHandler.html',1,'']]],
  ['basereaderhandler_3c_20typename_20schemadocumenttype_3a_3aschematype_3a_3aencodingtype_20_3e_4999',['BaseReaderHandler&lt; typename SchemaDocumentType::SchemaType::EncodingType &gt;',['../structBaseReaderHandler.html',1,'']]],
  ['basic_5fjson_5000',['basic_json',['../classbasic__json.html',1,'basic_json&lt; ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass &gt;'],['../classnlohmann_1_1basic__json.html',1,'nlohmann::basic_json&lt; ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType &gt;']]],
  ['basicistreamwrapper_5001',['BasicIStreamWrapper',['../classBasicIStreamWrapper.html',1,'']]],
  ['basicostreamwrapper_5002',['BasicOStreamWrapper',['../classBasicOStreamWrapper.html',1,'']]],
  ['biginteger_5003',['BigInteger',['../classinternal_1_1BigInteger.html',1,'internal']]],
  ['binary_5fop_5ft_5004',['binary_op_t',['../structxpath__parser_1_1binary__op__t.html',1,'xpath_parser']]],
  ['binary_5freader_5005',['binary_reader',['../classdetail_1_1binary__reader.html',1,'detail::binary_reader&lt; BasicJsonType, InputAdapterType, SAX &gt;'],['../classnlohmann_1_1detail_1_1binary__reader.html',1,'nlohmann::detail::binary_reader&lt; BasicJsonType, InputAdapterType, SAX &gt;']]],
  ['binary_5fwriter_5006',['binary_writer',['../classdetail_1_1binary__writer.html',1,'detail::binary_writer&lt; BasicJsonType, CharType &gt;'],['../classnlohmann_1_1detail_1_1binary__writer.html',1,'nlohmann::detail::binary_writer&lt; BasicJsonType, CharType &gt;']]],
  ['binarydata_5007',['BinaryData',['../structcereal_1_1BinaryData.html',1,'cereal']]],
  ['binaryinputarchive_5008',['BinaryInputArchive',['../classcereal_1_1BinaryInputArchive.html',1,'cereal']]],
  ['binaryoutputarchive_5009',['BinaryOutputArchive',['../classcereal_1_1BinaryOutputArchive.html',1,'cereal']]],
  ['bind_5fto_5farchives_5010',['bind_to_archives',['../structcereal_1_1detail_1_1bind__to__archives.html',1,'cereal::detail']]],
  ['binding_5fname_5011',['binding_name',['../structcereal_1_1detail_1_1binding__name.html',1,'cereal::detail']]],
  ['bindingtype_3c_20std_3a_3avector_3c_20t_2c_20allocator_20_3e_20_3e_5012',['BindingType&lt; std::vector&lt; T, Allocator &gt; &gt;',['../structemscripten_1_1internal_1_1BindingType_3_01std_1_1vector_3_01T_00_01Allocator_01_4_01_4.html',1,'emscripten::internal']]],
  ['boundaries_5013',['boundaries',['../structdetail_1_1dtoa__impl_1_1boundaries.html',1,'detail::dtoa_impl::boundaries'],['../structnlohmann_1_1detail_1_1dtoa__impl_1_1boundaries.html',1,'nlohmann::detail::dtoa_impl::boundaries']]],
  ['boundary_5014',['Boundary',['../classBoundary.html',1,'']]],
  ['byte_5fcontainer_5fwith_5fsubtype_5015',['byte_container_with_subtype',['../classbyte__container__with__subtype.html',1,'byte_container_with_subtype&lt; BinaryType &gt;'],['../classnlohmann_1_1byte__container__with__subtype.html',1,'nlohmann::byte_container_with_subtype&lt; BinaryType &gt;']]]
];
